// must always be sorted by length
export const RARITIES = [
  'Duel Terminal Normal Parallel Rare',
  'Duel Terminal Super Parallel Rare',
  'Duel Terminal Ultra Parallel Rare',
  'Duel Terminal Rare Parallel Rare',
  'Quarter Century Secret Rare',
  'Prismatic Secret Rare',
  'Platinum Secret Rare',
  'Duel Terminal Rare',
  'Super Short Print',
  'Extra Secret Rare',
  'Ultra Secret Rare',
  'Shatterfoil Rare',
  "Collector's Rare",
  'Starlight Rare',
  'Ultimate Rare',
  'Parallel Rare',
  'Platinum Rare',
  'Starfoil Rare',
  'Secret Rare',
  'Short Print',
  'Super Rare',
  'Ghost Rare',
  'Ultra Rare',
  'Common',
  'Rare',
];
