export const MICROSERVICES_GROUPS = {
  SCRAPE_GROUP: 'scrape',
} as const;

export const SCRAPE_TOPICS = {
  SCRAPE_CARDS: 'scrape-cards',
  SCRAPE_CARDS_FINISHED: 'scrape-cards-finished',
  MIGRATE_MARKET_URLS: 'migrate-market-urls',
} as const;

// must always be sorted by length
export const RARITIES = [
  'Duel Terminal Normal Parallel Rare',
  'Duel Terminal Super Parallel Rare',
  'Duel Terminal Ultra Parallel Rare',
  'Duel Terminal Rare Parallel Rare',
  'Quarter Century Secret Rare',
  'Prismatic Secret Rare',
  'Platinum Secret Rare',
  'Duel Terminal Rare',
  'Super Short Print',
  'Extra Secret Rare',
  'Ultra Secret Rare',
  'Shatterfoil Rare',
  "Collector's Rare",
  'Starlight Rare',
  'Ultimate Rare',
  'Parallel Rare',
  'Platinum Rare',
  'Starfoil Rare',
  'Secret Rare',
  'Short Print',
  'Super Rare',
  'Ghost Rare',
  'Ultra Rare',
  'Common',
  'Rare',
];

export const SKIP_URLS: Record<string, number> = {
  'https://yugioh.fandom.com/wiki/Hobby_League_participation_cards': 0,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_World_Championship_Qualifier_National_Championships_2011_prize_cards': 0,
  'https://yugioh.fandom.com/wiki/2-Player_Starter_Deck:_Yuya_&_Declan': 1,
  'https://yugioh.fandom.com/wiki/Structure_Deck:_Marik': 1,
  'https://yugioh.fandom.com/wiki/Battle_Pack_Tournament_Prize_Cards': 1,
  'https://yugioh.fandom.com/wiki/Duelist_League_participation_cards': 1,
  'https://yugioh.fandom.com/wiki/Pharaoh_Tour_promotional_cards': 1,
  'https://yugioh.fandom.com/wiki/Shonen_Jump_Championship_Series_Prize_Cards': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_World_Championship_prize_cards': 1,
  'https://yugioh.fandom.com/wiki/KC_Grand_Tournament_2022_prize_card': 1,
  'https://yugioh.fandom.com/wiki/Attack_of_the_Giant_Card!!': 1,
  'https://yugioh.fandom.com/wiki/Custom_Token_Card': 1,
  'https://yugioh.fandom.com/wiki/Duelist_League_Promotional_Cards_-_Konami_Series': 1,
  'https://yugioh.fandom.com/wiki/Special_Promotional_Cards': 1,
  "https://yugioh.fandom.com/wiki/Kids'_WB!_Duel_of_Destiny_promotional_card": 1,
  'https://yugioh.fandom.com/wiki/Tin_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/Booster_Pack_Collectors_Tins_2002': 1,
  'https://yugioh.fandom.com/wiki/Collectible_Tins_2003': 1,
  'https://yugioh.fandom.com/wiki/Duelist_Pack_Collection_Tin_2007': 1,
  'https://yugioh.fandom.com/wiki/2013_Collectible_Tins': 1,
  'https://yugioh.fandom.com/wiki/Non-Video_Game_Product_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Elemental_Hero_Collections': 1,
  'https://yugioh.fandom.com/wiki/Duel_Disk_-_Yusei_Version': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Adventskalender': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Advent_Calendar_(2018)': 1,
  'https://yugioh.fandom.com/wiki/Oversized_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/Case_Topper_promotional_cards': 1,
  'https://yugioh.fandom.com/wiki/Magazine_and_Manga_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/Shonen_Jump': 1,
  'https://yugioh.fandom.com/wiki/Banzai': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_The_Official_Magazine': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_The_Movie_Ani-Manga': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Duelist_Volume_16': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Millennium_World_Volume_4': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_R_Volume_1': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_R_Volume_3': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_R_Volume_4': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_R_Volume_5': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_1': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_2': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_3': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_4': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_5': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_6': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_7': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_8': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_GX_Volume_9': 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_1": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_2": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_3": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_4": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_5": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_6": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_7": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_8": 1,
  "https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_5D's_Volume_9": 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_1': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_2': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_3': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_4': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_5': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_6': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_7': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_8': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ZEXAL_Volume_9': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_1': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_2': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_3': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_4': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_5': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_6': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_ARC-V_Volume_7': 1,
  'https://yugioh.fandom.com/wiki/Special_Edition_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/The_Lost_Art_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Xbox': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Nintendo_DS': 1,
  'https://yugioh.fandom.com/wiki/Nightmare_Troubadour_Promotional_Cards': 1,
  'https://yugioh.fandom.com/wiki/Stardust_Accelerator_promotional_cards': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Game_Boy_Advance': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Nintendo_Game_Boy_Color': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Nintendo_GameCube': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Nintendo_Wii': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Nintendo_Switch_(NS)': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Personal_Computer_(PC)': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Power_of_Chaos:_Kaiba_the_Revenge': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Sony_Playstation_(PS)': 1,
  'https://yugioh.fandom.com/wiki/Yu-Gi-Oh!_Forbidden_Memories_Premium_Edition_promotional_cards': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Sony_Playstation_2_(PS2)': 1,
  'https://yugioh.fandom.com/wiki/Video_Game_Promotional_Cards_-_Sony_Playstation_Portable_(PSP)': 1,
  'https://yugioh.fandom.com/wiki/Duel_Terminal': 1,
};

export enum GroupByType {
  CARD_NAME = 'cardName',
  SET_NAME = 'setName',
  SET_CODE = 'setCode',
}

export enum OrderByType {
  CARD_NAME = 'cardName',
  SET_NAME = 'setName',
  SET_CODE = 'setCode',
  COUNT = 'count',
}

export enum SortType {
  ASC = 'ASC',
  DESC = 'DESC',
}
